### ISSUE TITLE
Regarding styles rendered in head tag of application using dom-module

### ISSUE THREAD

**Issue by jaspreet1234567** [vaadin/vaadin#46]
Hi,

I am using a Vaadin controls in our application (lit-element and polymer). I saw the styles of vaadin component are rendered in head tag under "dom-module". I am want to confirm that why these styles are rendered in head tag rather than being the part of shadow-dom. 

Also, when a route is changed and vaadin components are removed from dom then these styles are still there in head tag.

Is there a way to render these styles as a part of shadow dom rather than head tag.

Please suggest us.

Thanks.

**Comment by web-padawan** [comment]
Thanks for the issue. The styles are there because of [ThemableMixin](https://github.com/vaadin/vaadin-themable-mixin), which provides a way for styling Vaadin components until all browsers support CSS Shadow Parts out of the box.

ES modules versions of Vaadin components are creating these on the flight, as the components are published using `polymer-modulizer` conversion tool. In particular, it produces such code:

```js
const $_documentContainer = document.createElement('template');

$_documentContainer.innerHTML = `<dom-module id="vaadin-dialog-overlay-styles" theme-for="vaadin-dialog-overlay">
  <template>
    <style>
      [part="content"] {
        min-width: 12em; /* matches the default <vaadin-text-field> width */
      }
    </style>
  </template>
</dom-module>`;

document.head.appendChild($_documentContainer.content);
```

For the time being the presence of these `<style>` tags is necessary. They shouldn't affect the performance in any way. At the same time, trying to remove them dynamically would require us to track all the instances of every single component on the page, and could be complicated.

We will soon start work on converting our codebase to Polymer 3 (and LitElement), and later on will come up with a better theming mechanism, so this is also something for us to cover in future.
