### ISSUE TITLE
DataProvider 2

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/vaadin#55]
Our current interfaces to connect data (lazily) to components such as Grid and ComboBox have shortcomings that make it difficult or impossible to use in certain situations, such as when the backend only allows paged access or when calculating the size of resultset is slow or not supported at all.

**Comment by markusherr** [comment]
I also would like to mention, that is very hard to handle errors gracefully ,for example in an BackendDataProvider, especially if the error occurs in fetchFromBackend or if the size reported by sizeInBackend and the number of items returned by fetchFromBackend differ. THat can always happen, because its two separate calls and the number of items in the backend can change between those calls.

**Comment by web-padawan** [comment]
This was released in Vaadin 17 for Grid and Vaadin 18 for ComboBox.
