### ISSUE TITLE
Receiving pro subscription message when not using pro components

### ISSUE THREAD

**Issue by tm2josep** [vaadin/vaadin#58]
I'm not using any of the Vaadin Pro web components, but I keep seeing the message over my application that I need to go get the license. 

Here is the piece of code which lists all of the components I am using:

Promise.all([
    customElements.whenDefined("vaadin-list-box"),
    customElements.whenDefined("vaadin-item"),
    customElements.whenDefined("vaadin-button"),
    customElements.whenDefined("vaadin-grid")
])

And I import them individually. 
I do not use grid pro, only grid. 

What should I do?

**Comment by web-padawan** [comment]
Are you using Vaadin for Java, or JS components only?

**Comment by web-padawan** [comment]
We have updated all the Pro components so that they only run license checker when used.

This means that even if you import a Pro component like charts by accident, but do not add actual `vaadin-charts` HTML element to your app, there will be no license checker popup anymore. 

As this has been resolved and tested on our side, I'm closing this as fixed. 
Please let us know if you are still experiencing any problems and we will investigate.
