### ISSUE TITLE
Use vaadin-select with Vite

### ISSUE THREAD

**Issue by ais-one** [vaadin/vaadin#71]
The dropdown does not work on Vite

Please see example repo below. The code is in the HelloWorld Vue component.

just clone, install and run dev

https://github.com/ais-one/vite-vaadin

**Comment by tomivirkki** [comment]
Hi
You should use the `renderer` API instead of `<template>` which is meant for Polymer apps only (there's hardly any documentation about this unfortunately :/ ). For the next generation of Vaadin components, we're planning to remove the support for `<template>` completely and only have the `renderer` API.

The example app should be modified as follows:
```html
<vaadin-select label="Label" :renderer="selectRenderer"></vaadin-select>
```

```js
export default {
  ...,
  methods: {
    selectRenderer(root) {
      // I'm not familiar enough with Vue to use proper templating here. Use of innerHTML is naturally discouraged when rendering any non-static content
      if (!root.firstElementChild) {
        root.innerHTML = `
          <vaadin-list-box>
            <vaadin-item>Option one</vaadin-item>
            <vaadin-item>Option two</vaadin-item>
          </vaadin-list-box>
        `;
      }
    }
  },
```
